### ISSUE TITLE
Feed links changes

### ISSUE THREAD

**Issue by MarZab** [solarissmoke/disable-comments-mu#11]
WordPress 4.4.0 made some changes to the way it inserts the feed links.

We can remove the feed_links override and add a filter on 'feed_links_show_comments_feed' instead.

https://github.com/WordPress/WordPress/blob/3e2e0c52e6c9363068abc169fe048346bd8baa12/wp-includes/general-template.php#L2585

https://github.com/solarissmoke/disable-comments-mu/blob/master/disable-comments-mu.php#L163

I'm a bit lost for time, ill try yo make a patch as soon as I can.

**Comment by solarissmoke** [comment]
Thanks! - was working on the full version of the plugin today so have patched this.
