### ISSUE TITLE
Test coverage planned

### ISSUE THREAD

**Issue by etherealite** [solarissmoke/disable-comments-mu#12]
Are there plans for a set of integration tests to be implemented for this plugin?

**Comment by szepeviktor** [comment]
See the main plugin https://github.com/solarissmoke/disable-comments

**Comment by solarissmoke** [comment]
I am unlikely to find time for this in the next 3-6 months. PR is welcome!

**Comment by solarissmoke** [comment]
The repo now has a test suite that covers the plugin's core functionality.

**Comment by etherealite** [comment]
Awesome, I'm so very glad to see this! Thank you very much @solarissmoke.
